### PR TITLE
"Root_Query" class implemented.

### LINKED ISSUE #299: Unable to query 'Orders' under Root
**Describe the bug**
Not sure if this is a bug or by design, but it causes usability issue. I am unable to query `Orders` under `Root`.
```
query GetOrders {
    orders{
        edges{
            node{
                orderId
           }
        }
    }
}
```
But it works for query `Customer.Orders`
```
query GetCustomer(
     customer(
         customerId: 8
     ){
            ...otherFields
            orders{
                 edges{
                      node{
                          orderId
                       }
                 }
            }
     }
}
```
For both queries, i had the customer logged in with valid jwt access token. It causes some problems, for example, pagination of customer orders. I will be able to fetch the first page of orders together with `Customer.Orders`, but for the subsequent pages i will need to fetch more orders together with the redundant `Customer` orther fields.

**To Reproduce**
1. Log in as customer
2. query customer's orders using root query 
3. you should get an empty array for the orders field

**Expected behavior**
Return of a list of orders belongs to the logged customer.

**Additional context**
wp-graph-woocommerce 0.5.1

### PR DESCRIPTION
**Pull request by kidunot89**
### Your checklist for this pull request
Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.

🚨Please review the [guidelines for contributing](./CONTRIBUTING.md) to this repository.

- [x] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
- [x] Make sure you are requesting to pull request from a **topic/feature/bugfix branch** (right side). Don't pull request from your master!

What does this implement/fix? Explain your changes.
---------------------------------------------------
- Centralizes all root queries in the `WPGraphQL\WooCommerce\Type\WPObject\Root_Query` class.
- The root `orders{...}` query, defaults to the same results as `customer{ orders{ ... } }` if a user lacking the `shop_manager` capabilities is authenticated. 

Does this close any currently open issues?
------------------------------------------
Fixes #299 

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

Where has this been tested?
---------------------------
**Operating System:** Ubuntu 20.04

**WordPress Version:** 5.4.2

### CODE REVIEW

File: includes/type/object/class-root-query.php [hunk 1]
```diff
@@ -0,0 +1,677 @@
...
+					if ( $token_invalid ) {
+						throw new UserError( $token_invalid );
+					}
+
+					return Factory::resolve_cart();
+				},
+			)
+		);
+
+		register_graphql_field(
```
Comment (jasonbahl) [inline includes/type/object/class-root-query.php:43]: You could also do `register_graphql_fields( 'RootQuery' $array_of_fields );`

Comment (kidunot89) [reply includes/type/object/class-root-query.php:43]: I know, I pretty much just copied and pasted the logic from the `type` classes.

Comment (jasonbahl) [reply includes/type/object/class-root-query.php:43]: word. no biggie just thought I'd point it out. 😄
